### ISSUE TITLE
[Visualization network]

### ISSUE THREAD

**Issue by tranmanhdat** [flashlight/wav2letter#836]
### Feature Description
Use nework.arch to visualization network or have exist images for network.arch

#### Use Case
More detail about network using to train

**Comment by vineelpratap** [comment]
Hi, 
 We use`nework.arch` to make it easy for the user to understand the network (compared to defining arch file using json configs that are typically used in ML community). Also, once you load the model, you can use `network->prettyString()` to the print the architecture file. 
 If you are looking for a visualization, we don't support that. Do you have any reference from other codebases that you are looking for ?

**Comment by tranmanhdat** [comment]
i usually use [Netron](https://github.com/lutzroeder/netron) to visualize model, it's a bit difficult for me to imagaze model
