### ISSUE TITLE
how can i generate feature by mfsc then save to hdf5 file for faster load feature when training?

### ISSUE THREAD

**Issue by trangtv57** [flashlight/wav2letter#911]
### Question
hi.
I want make more augmentation for my audio with some noise using sox like kaldi, but if audio generate and save physical it's take so large storage. So i want generate my audio augmentation then convert it to feature using mfsc (may be using python of wav2letter) for reduce storage also make faster loading feature for training.
My problem:  how to generate audio to mfsc feature save to hdf5 and wav2letter can use.
So can you give me some suggest how can i start?
thanks you

**Comment by tlikhomanenko** [comment]
Are you gonna to train acoustic model with w2l or with something else?

**Comment by trangtv57** [comment]
hi @tlikhomanenko 
I am going to train  AM with w2l, but instead read input from file, i want to use direct feature pre-generate to mfsc for faster loading and  take low storage.

**Comment by tlikhomanenko** [comment]
We don't have this option right from the box. You need to do extra a bit of coding. Can point you where to look. Here is the place where featurization happens https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/Featurize.cpp#L111 (all above). So you can simply store this on the disk (please be sure to run with batchsize=1 to have each sample separately). Then you need to add loading of samples in the same place with some flag that you needd to read pre-computed features, and just read in the same way as you stored.

**Comment by trangtv57** [comment]
thanks you @tlikhomanenko, I will follow your instruction,

**Comment by trangtv57** [comment]
hi @tlikhomanenko 
I understand your instruction and i have followed guide to use wav2vec as feature for wav2letter, but i have one more problem.
I want save infeat and feat.inputDims for each sample from this step, 
https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/Featurize.cpp#L103
like :
```
std::string fileNameSavePreData;
    fileNameSavePreData = getPreSaveDataFile(format("pre_data_%03s.bin", feat.sampleIds[0]), FLAGS_folder_save_predata);   
    vector<float> feature;
    W2lSerializer::save(fileNameSavePreData, infeat);
```
I save after featurize each sample, then after i can save all data i just load it in W2lListFilesDataset.cpp after line
https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/W2lListFilesDataset.cpp#L80

    ```
if (FLAGS_loadpreft) {
      std::string fileNameSavePreData;
      fileNameSavePreData = getPreSaveDataFile(format("pre_data_%03s.bin", data[id].sampleId), FLAGS_savepredata);   
      vector<float> feature;
      W2lSerializer::load(fileNameSavePreData, feature);
      data[id].input = feature;
    } else {
      data[id].input = loadSound(data_[i].getAudioFile());
    }
```
I hope you can understand my idea, and 1 problem is the shape data i save from featureize.cpp how to mapping when combine from input of featurize like normal.
Thanks you, hope you reply soon

**Comment by tlikhomanenko** [comment]
For saving all info you can do:

```
W2lSerializer::save(fileNameSavePreData, infeat.dims(0), infeat.dims(1), infeat.dims(2), infeat.dims(3), feature);
```

and then after loading you know what size and std::vector and just create necessary data. Does this make sense?

**Comment by zxpan** [comment]
@trangtv57 is this a very interesting idea to save the features in hdf5, is it possible for you to share your code?
