### ISSUE TITLE
pip install -e . run error

### ISSUE THREAD

**Issue by askinucuncu** [flashlight/wav2letter#943]
ERROR: Command errored out with exit status 1:
     command: /home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/
    Complete output (201 lines):
    running develop
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    reading manifest file 'wav2letter.egg-info/SOURCES.txt'
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- CUDA found (library: /usr/local/cuda-11.0/lib64/libcudart_static.a;Threads::Threads;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda-11.0/include)
    -- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [Accelerate]
    -- Checking for [vecLib]
    -- Checking for [cblas - atlas]
    -- Includes found
    -- Looking for cblas_dgemm
    -- Looking for cblas_dgemm - found
    -- CBLAS Symbols FOUND
    -- CBLAS library found
    -- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so)
    -- Found FFTW: /usr/local/include
    -- FFTW found
    -- Looking for KenLM
    -- Using kenlm library found in /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm/build/lib/libkenlm.a
    -- Using kenlm utils library found in /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm/build/lib/libkenlm.a
    -- kenlm lm/model.hh found in /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm/lm/model.hh
    -- Found kenlm: /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm
    -- Found kenlm (include: /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm, library: /home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm/build/lib/libkenlm.a;/home/bcode/wav2vac/self-supervised-speech-recognition/libs/kenlm/build/lib/libkenlm_util.a)
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Found LibLZMA: /usr/lib/x86_64-linux-gnu/liblzma.so (found version "5.2.4")
    -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8")
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
    -- Found PythonInterp: /home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/bin/python (found version "3.8.5")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8
    Scanning dependencies of target CUB
    Scanning dependencies of target pybind11
    [  0%] Creating directories for 'CUB'
    [  1%] Creating directories for 'pybind11'
    [  1%] Performing download step (git clone) for 'pybind11'
    [  2%] Performing download step (git clone) for 'CUB'
    Cloning into 'CUB'...
    Cloning into 'pybind11'...
    Note: switching to '9a19306fbf30642ca331d0ec88e7da54a96860f9'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:
    
      git switch -c <new-branch-name>
    
    Or undo this operation with:
    
      git switch -
    
    Turn off this advice by setting config variable advice.detachedHead to false
    
    HEAD is now at 9a19306 bump version to 2.2.4
    Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
    Cloning into '/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/bindings/python/pybind11/src/pybind11/tools/clang'...
    Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
    [  3%] Performing update step for 'pybind11'
    [  3%] No patch step for 'pybind11'
    [  4%] No configure step for 'pybind11'
    [  5%] No build step for 'pybind11'
    [  6%] No install step for 'pybind11'
    [  6%] Completed 'pybind11'
    [  6%] Built target pybind11
    Note: switching to 'c3cceac115c072fb63df1836ff46d8c60d9eb304'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by switching back to a branch.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -c with the switch command. Example:
    
      git switch -c <new-branch-name>
    
    Or undo this operation with:
    
      git switch -
    
    Turn off this advice by setting config variable advice.detachedHead to false
    
    HEAD is now at c3cceac1 update readme to 1.8.0
    [  6%] Performing update step for 'CUB'
    [  7%] No patch step for 'CUB'
    [  8%] No configure step for 'CUB'
    [  8%] No build step for 'CUB'
    [  9%] No install step for 'CUB'
    [  9%] Completed 'CUB'
    [  9%] Built target CUB
    [ 10%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ViterbiPath.cu.o
    [ 10%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_CriterionUtils.cu.o
    [ 11%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o
    [ 11%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_FullConnectionCriterion.cu.o
    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    CMake Error at w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o.Release.cmake:220 (message):
      Error generating
      /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o
    
    
    CMake Error at w2l-criterion-library-cuda_generated_CriterionUtils.cu.o.Release.cmake:220 (message):
      Error generating
      /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_CriterionUtils.cu.o
    
    
    CMake Error at w2l-criterion-library-cuda_generated_ViterbiPath.cu.o.Release.cmake:220 (message):
      Error generating
      /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_ViterbiPath.cu.o
    
    
    CMake Error at w2l-criterion-library-cuda_generated_FullConnectionCriterion.cu.o.Release.cmake:220 (message):
      Error generating
      /home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/build/temp.linux-x86_64-3.8/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_FullConnectionCriterion.cu.o
    
    
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:84: src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_CriterionUtils.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:105: src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ViterbiPath.cu.o] Error 1
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:91: src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o] Error 1
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:98: src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_FullConnectionCriterion.cu.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:274: src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/all] Error 2
    make: *** [Makefile:103: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py", line 95, in <module>
        setup(
      File "/home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py", line 90, in build_extensions
        subprocess.check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/bcode/.local/share/virtualenvs/wav2vac-D4F79Hly/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/bcode/wav2vac/self-supervised-speech-recognition/libs/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

OS: Ubuntu 20.04
Cuda: 11.0
Kenlm : echo $KENLM_ROOT_DIR /home/bcode/SpeechRec/wav2-speech-recognition/libs/kenlm/

**Comment by askinucuncu** [comment]
As suggested, I removed the build folder. It didn't happen again

**Comment by tlikhomanenko** [comment]
The error is `nvcc fatal   : Unsupported gpu architecture 'compute_30'`. So you have very recent cuda version, probably we didn't have the fix for it in the version you are trying. 

Either use docker image of the same commit or please switch to the recent version of bindings which will work with Cuda 11 https://github.com/facebookresearch/flashlight/tree/master/bindings/python.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if this suggestion didn't resolve the issue for you (for flashlight version of python bindings please create issue directly in the flashlight git).

**Comment by askinucuncu** [comment]
I made the CUDA version 10.1. However, the same error occurs again

**Comment by tlikhomanenko** [comment]
what is GPU card?

**Comment by rishabbjain** [comment]
i'm facing the same issue, i have cuda version=11.4. did you resolve it?
