### ISSUE TITLE
[VoxPopuli Models] Adding VoxPopuli models to wav2letter/recipes

### ISSUE THREAD

**Issue by Molugan** [flashlight/wav2letter#957]
### Feature Description
We would like to add the checkpoints trained with wav2letter on VoxPopuli's 100k hours of data. The model was trained using https://github.com/facebookresearch/wav2letter/tree/masked_cpc/recipes/joint_training, however, the code developed in this branch doesn't handle the pre-training. But with 100kh of unlabelled data, pre-training becomes a necessary feature.

The recipe code is currently available in https://github.com/Molugan/wav2letter/tree/RECIPE_voxpopuli/recipes/voxpopuli and I would like to start a pull request.

#### Use Case
VoxPopuli (https://arxiv.org/abs/2101.00390) is a large, multilingual dataset with 100kh of data in 23 languages. A model pretrained on VoxPopuli can be transferred easily for some ASR tasks with a little amount of labelled data (see https://github.com/Molugan/wav2letter/blob/RECIPE_voxpopuli/recipes/voxpopuli/README.md).

**Comment by tlikhomanenko** [comment]
Landed.
