### ISSUE TITLE
[TDS model with transducer]

### ISSUE THREAD

**Issue by jinggaizi** [flashlight/wav2letter#964]
### Question
transducer loss is better than ctc in  paper https://arxiv.org/pdf/2011.04785.pdf. it's use LC-BLSTM as encoder to compare 3 loss ,have you try to train a TDS-transducer, is it better than TDS-ctc?

**Comment by tlikhomanenko** [comment]
As far as I know we didn't try transducer, so welcome to test it too! To be sure  cc @vineelpratap @xuqiantong. 

Would be happy if you share later your results here.

**Comment by vineelpratap** [comment]
Hi @jinggaizi, we haven't tried running TDS with transducer. So, can't comment on the performance.
