### ISSUE TITLE
Use seq2seq librispeech models

### ISSUE THREAD

**Issue by giannisp-verneek** [flashlight/wav2letter#975]
I am trying out the wav2letter++ example that you have using the docker image from the `inf build` branch. How can I use the models that are here: https://github.com/flashlight/wav2letter/tree/master/recipes/seq2seq_tds/librispeech with that version? I'm trying to load them and I'm getting the following message when the language model tries to load:

```
Loading the LM will be faster if you build a binary file.
Reading /root/Git/Projects/model/lm_librispeech_convlm_14B.bin
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  /tmp/kenlm/lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException.
first non-empty line was "
```

**Comment by tlikhomanenko** [comment]
You are trying to use convlm model not the kenlm, so you need to specify flag on language model to be convlm or please put lm path as some kenlm model (bin or arpa).
