### ISSUE TITLE
simple streaming inference example and GPU

### ISSUE THREAD

**Issue by giannisp-verneek** [flashlight/wav2letter#980]
Does the wav2letter simple streaming inference examples use GPUs when executing? I am using the [`wav2letter/wav2letter:cuda-latest`](https://hub.docker.com/layers/wav2letter/wav2letter/cuda-latest/images/sha256-ba0c6fb245231911c8ea939d3823c9f4d350a1978e1a2ca71ddc9584a310d3a2?context=explore). If yes, how can I verify that my GPU is used? Checking `nvidia-smi` does not offer much information.

Thank you!

**Comment by tlikhomanenko** [comment]
cc @vineelpratap

**Comment by joazoa** [comment]
use nvtop
