### ISSUE TITLE
incorrect sys.argv index at wav2letter/recipes/sota/2019/lm_corpus_and_PL_generation/generate_uniq.py

### ISSUE THREAD

**Issue by Splend1d** [flashlight/wav2letter#988]
### Bug Description
the sys.argv index of wav2letter/recipes/sota/2019/lm_corpus_and_PL_generation/generate_uniq.py, line10 is incorrect.
Following the readme, this leads to out of index error

#### Reproduction Steps
follow the readme in recipes/sota/2019/lm_corpus_and_PL_generation, the error occurs when executing
`python3 generate_uniq.py librispeech_lm_corpus_raw_without_librivox.txt.norm`

**Comment by tlikhomanenko** [comment]
PR https://github.com/flashlight/wav2letter/pull/989
